// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts
/*
If you want to add custom formats, create a file in this folder named: "custom-formats.ts"

Paste the following code into the file and add your desired formats and their sections between the brackets:
--------------------------------------------------------------------------------
// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts

export const Formats: FormatList = [
];
--------------------------------------------------------------------------------

If you specify a section that already exists, your format will be added to the bottom of that section.
New sections will be added to the bottom of the specified column.
The column value will be ignored for repeat sections.
*/

export const Formats: import("../sim/dex-formats").FormatList = [
	// S/V Singles
	///////////////////////////////////////////////////////////////////

	{
		section: "S/V Singles",
	},
	{
		name: "[Gen 9] Random Battle",
		desc: `Randomized teams of Pok&eacute;mon with sets that are generated to be competitively viable.`,
		mod: "gen9",
		team: "random",
		bestOfDefault: true,
		ruleset: [
			"PotD",
			"Obtainable",
			"Species Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Sleep Clause Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 9] Unrated Random Battle",
		mod: "gen9",
		team: "random",
		challengeShow: false,
		rated: false,
		ruleset: [
			"Obtainable",
			"Species Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Sleep Clause Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 9] Free-For-All Random Battle",
		mod: "gen9",
		team: "randomFFA",
		gameType: "freeforall",
		tournamentShow: false,
		rated: false,
		ruleset: [
			"Obtainable",
			"Species Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Sleep Clause Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 9] Random Battle (Blitz)",
		mod: "gen9",
		team: "random",
		bestOfDefault: true,
		ruleset: ["[Gen 9] Random Battle", "Blitz"],
	},
	{
		name: "[Gen 9] Multi Random Battle",
		mod: "gen9",
		team: "random",
		gameType: "multi",
		searchShow: false,
		tournamentShow: false,
		rated: false,
		ruleset: [
			"Max Team Size = 3",
			"Obtainable",
			"Species Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Sleep Clause Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 9] OU",
		mod: "gen9",
		ruleset: [
			"Standard",
			"Evasion Abilities Clause",
			"Sleep Moves Clause",
			"!Sleep Clause Mod",
		],
		banlist: [
			"Uber",
			"AG",
			"Arena Trap",
			"Moody",
			"Shadow Tag",
			"King's Rock",
			"Razor Fang",
			"Baton Pass",
			"Last Respects",
			"Shed Tail",
		],
	},
	{
		name: "[Gen 9] Ubers",
		mod: "gen9",
		ruleset: ["Standard"],
		banlist: [
			"AG",
			"Moody",
			"King's Rock",
			"Razor Fang",
			"Baton Pass",
			"Last Respects",
		],
	},
	{
		name: "[Gen 9] UU",
		mod: "gen9",
		ruleset: ["[Gen 9] OU"],
		banlist: ["OU", "UUBL"],
	},
	{
		name: "[Gen 9] RU",
		mod: "gen9",
		ruleset: ["[Gen 9] UU"],
		banlist: ["UU", "RUBL", "Light Clay"],
	},
	{
		name: "[Gen 9] NU",
		mod: "gen9",
		ruleset: ["[Gen 9] RU"],
		banlist: ["RU", "NUBL", "Drought", "Quick Claw"],
	},
	{
		name: "[Gen 9] PU",
		mod: "gen9",
		ruleset: ["[Gen 9] NU"],
		banlist: ["NU", "PUBL", "Damp Rock"],
	},
	{
		name: "[Gen 9] LC",
		mod: "gen9",
		ruleset: ["Little Cup", "Standard"],
		banlist: [
			"Aipom",
			"Basculin-White-Striped",
			"Cutiefly",
			"Diglett-Base",
			"Dunsparce",
			"Duraludon",
			"Flittle",
			"Gastly",
			"Girafarig",
			"Gligar",
			"Magby",
			"Meditite",
			"Misdreavus",
			"Murkrow",
			"Porygon",
			"Qwilfish-Hisui",
			"Rufflet",
			"Scraggy",
			"Scyther",
			"Sneasel",
			"Sneasel-Hisui",
			"Snivy",
			"Stantler",
			"Torchic",
			"Voltorb-Hisui",
			"Vulpix",
			"Vulpix-Alola",
			"Yanma",
			"Moody",
			"Heat Rock",
			"Baton Pass",
			"Sticky Web",
		],
	},
	{
		name: "[Gen 9] Monotype",
		mod: "gen9",
		ruleset: [
			"Standard",
			"Evasion Abilities Clause",
			"Same Type Clause",
			"Terastal Clause",
		],
		banlist: [
			"Annihilape",
			"Arceus",
			"Baxcalibur",
			"Calyrex-Ice",
			"Calyrex-Shadow",
			"Chi-Yu",
			"Chien-Pao",
			"Blaziken",
			"Deoxys-Normal",
			"Deoxys-Attack",
			"Dialga",
			"Dialga-Origin",
			"Espathra",
			"Eternatus",
			"Giratina",
			"Giratina-Origin",
			"Gouging Fire",
			"Groudon",
			"Ho-Oh",
			"Iron Bundle",
			"Kingambit",
			"Koraidon",
			"Kyogre",
			"Kyurem-Black",
			"Kyurem-White",
			"Lugia",
			"Lunala",
			"Magearna",
			"Mewtwo",
			"Miraidon",
			"Necrozma-Dawn-Wings",
			"Necrozma-Dusk-Mane",
			"Palafin",
			"Palkia",
			"Palkia-Origin",
			"Rayquaza",
			"Reshiram",
			"Shaymin-Sky",
			"Solgaleo",
			"Ursaluna-Bloodmoon",
			"Urshifu-Single-Strike",
			"Zacian",
			"Zacian-Crowned",
			"Zamazenta",
			"Zamazenta-Crowned",
			"Zekrom",
			"Moody",
			"Shadow Tag",
			"Booster Energy",
			"Damp Rock",
			"Focus Band",
			"King's Rock",
			"Quick Claw",
			"Razor Fang",
			"Smooth Rock",
			"Baton Pass",
			"Last Respects",
			"Shed Tail",
		],
	},
	{
		name: "[Gen 9] CAP",
		desc: "The Create-A-Pok&eacute;mon project is a community dedicated to exploring and understanding the competitive Pok&eacute;mon metagame by designing, creating, and playtesting new Pok&eacute;mon concepts.",
		mod: "gen9",
		ruleset: ["[Gen 9] OU", "+CAP"],
		banlist: ["Crucibellite", "Rage Fist"],
	},
	{
		name: "[Gen 9] BSS Reg I",
		mod: "gen9",
		searchShow: false,
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Limit Two Restricted",
		],
		restricted: ["Restricted Legendary"],
	},
	{
		name: "[Gen 9] BSS Reg J",
		mod: "gen9",
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Limit Two Restricted",
		],
		restricted: ["Restricted Legendary", "Mythical"],
	},
	{
		name: "[Gen 9] Custom Game",
		mod: "gen9",
		searchShow: false,
		debug: true,
		battle: { trunc: Math.trunc },
		// no restrictions, for serious (other than team preview)
		ruleset: [
			"Team Preview",
			"Cancel Mod",
			"Max Team Size = 24",
			"Max Move Count = 24",
			"Max Level = 9999",
			"Default Level = 100",
		],
	},

	// S/V Doubles
	///////////////////////////////////////////////////////////////////

	{
		section: "S/V Doubles",
	},
	{
		name: "[Gen 9] Random Doubles Battle",
		mod: "gen9",
		gameType: "doubles",
		team: "random",
		bestOfDefault: true,
		ruleset: [
			"PotD",
			"Obtainable",
			"Species Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Illusion Level Mod",
			"Sleep Clause Mod",
		],
	},
	{
		name: "[Gen 9] Doubles OU",
		mod: "gen9",
		gameType: "doubles",
		ruleset: ["Standard Doubles", "Evasion Abilities Clause"],
		banlist: ["DUber", "Shadow Tag", "Commander"],
	},
	{
		name: "[Gen 9] Doubles Ubers",
		mod: "gen9",
		gameType: "doubles",
		ruleset: ["Standard Doubles", "!Gravity Sleep Clause"],
	},
	{
		name: "[Gen 9] Doubles UU",
		mod: "gen9",
		gameType: "doubles",
		ruleset: ["[Gen 9] Doubles OU"],
		banlist: ["DOU", "DBL"],
	},
	{
		name: "[Gen 9] Doubles LC",
		mod: "gen9",
		gameType: "doubles",
		searchShow: false,
		ruleset: ["Standard Doubles", "Little Cup", "Sleep Clause Mod"],
		banlist: [
			"Basculin-White-Striped",
			"Dunsparce",
			"Duraludon",
			"Girafarig",
			"Gligar",
			"Misdreavus",
			"Murkrow",
			"Qwilfish-Hisui",
			"Scyther",
			"Sneasel",
			"Sneasel-Hisui",
			"Stantler",
			"Vulpix",
			"Vulpix-Alola",
			"Yanma",
		],
	},
	{
		name: "[Gen 9] VGC 2023 Reg C",
		mod: "gen9predlc",
		gameType: "doubles",
		searchShow: false,
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Open Team Sheets",
			"Paldea Pokedex",
		],
	},
	{
		name: "[Gen 9] VGC 2023 Reg D",
		mod: "gen9predlc",
		gameType: "doubles",
		searchShow: false,
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Open Team Sheets",
		],
		banlist: ["Walking Wake", "Iron Leaves"],
	},
	{
		name: "[Gen 9] VGC 2024 Reg G",
		mod: "gen9",
		gameType: "doubles",
		searchShow: false,
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Open Team Sheets",
			"Limit One Restricted",
		],
		restricted: ["Restricted Legendary"],
	},
	{
		name: "[Gen 9] VGC 2025 Reg I",
		mod: "gen9",
		gameType: "doubles",
		searchShow: false,
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Open Team Sheets",
			"Limit Two Restricted",
		],
		restricted: ["Restricted Legendary"],
	},
	{
		name: "[Gen 9] VGC 2025 Reg J",
		mod: "gen9",
		gameType: "doubles",
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Limit Two Restricted",
		],
		restricted: ["Restricted Legendary", "Mythical"],
	},
	{
		name: "[Gen 9] VGC 2025 Reg J (Bo3)",
		mod: "gen9",
		gameType: "doubles",
		searchShow: false,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Force Open Team Sheets",
			"Best of = 3",
			"Limit Two Restricted",
		],
		restricted: ["Restricted Legendary", "Mythical"],
	},
	{
		name: "[Gen 9] VGC 2026 Reg F",

		mod: "gen9",
		gameType: "doubles",
		bestOfDefault: true,
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Open Team Sheets",
		],
	},
	{
		name: "[Gen 9] VGC 2026 Reg F (Bo3)",

		mod: "gen9",
		gameType: "doubles",
		ruleset: [
			"Flat Rules",
			"!! Adjust Level = 50",
			"Min Source Gen = 9",
			"VGC Timer",
			"Force Open Team Sheets",
			"Best of = 3",
		],
	},
	{
		name: "[Gen 9] Doubles Custom Game",
		mod: "gen9",
		gameType: "doubles",
		searchShow: false,
		battle: { trunc: Math.trunc },
		debug: true,
		// no restrictions, for serious (other than team preview)
		ruleset: [
			"Team Preview",
			"Cancel Mod",
			"Max Team Size = 24",
			"Max Move Count = 24",
			"Max Level = 9999",
			"Default Level = 100",
		],
	},

	// National Dex
	///////////////////////////////////////////////////////////////////

	{
		section: "National Dex",
	},
	{
		name: "[Gen 9] National Dex",
		mod: "gen9",
		ruleset: ["Standard NatDex", "Terastal Clause"],
		banlist: [
			"ND Uber",
			"ND AG",
			"Arena Trap",
			"Moody",
			"Power Construct",
			"Shadow Tag",
			"King's Rock",
			"Quick Claw",
			"Razor Fang",
			"Assist",
			"Baton Pass",
			"Last Respects",
			"Shed Tail",
		],
	},
	{
		name: "[Gen 8] National Dex",
		mod: "gen8",
		ruleset: ["Standard NatDex", "Dynamax Clause"],
		banlist: [
			"ND Uber",
			"Arena Trap",
			"Moody",
			"Power Construct",
			"Shadow Tag",
			"King's Rock",
			"Razor Fang",
			"Quick Claw",
			"Baton Pass",
		],
	},
];
